server:
  port: 8084

ws:
  config:
    handshakeEndpoint: /ws/trivia
    brokerPrefix: /ws/topic
    applicationDestinationPrefix: /ws/app
  topic:
    players: ${ws.config.brokerPrefix}/players

api:
  users: http://localhost:8081